from pathlib import Path
from rubymarshal.reader import loads
from rubymarshal.writer import writes
from rubymarshal.classes import RubyObject, Symbol
G=Path(__file__).resolve().parent.parent
enc=loads((G/'Data/encounters.dat').read_bytes())
rosters={103:[(45,'CATERPIE',3,5),(40,'WEEDLE',3,5),(15,'WURMPLE',3,5)],108:[(40,'ZIGZAGOON',4,6),(35,'SUNKERN',4,6),(15,'EKANS',4,6),(10,'PSYDUCK',4,6)]}
species=loads((G/'Data/species.dat').read_bytes())
text='# Tidebound field encounters. Generated by Development/rebuild_field_data.py\n'
for mid,rows in rosters.items():
 for _,name,_,_ in rows:assert Symbol(name) in species,name
 key=Symbol(f'{mid}_0')
 enc[key]=RubyObject('GameData::Encounter',{'@id':key,'@map':mid,'@version':0,'@step_chances':{Symbol('Land'):18},'@types':{Symbol('Land'):[[w,Symbol(n),lo,hi] for w,n,lo,hi in rows]},'@pbs_file_suffix':'tidebound'})
 text+=f'#-------------------------------\n[{mid}]\nLand,18\n'+''.join(f'    {w},{n},{lo},{hi}\n' for w,n,lo,hi in rows)
(G/'Data/encounters.dat').write_bytes(writes(enc))
(G/'PBS/encounters_tidebound.txt').write_text(text)
print('Compiled forest bugs and coastal Zigzagoon/Sunkern/Ekans/Psyduck encounters.')
