"""Add regional form data without modifying ordinary Sunkern or existing saves."""
from pathlib import Path
from rubymarshal.reader import loads
from rubymarshal.writer import writes
from rubymarshal.classes import Symbol
G=Path(__file__).resolve().parent.parent
species=loads((G/'Data/species.dat').read_bytes())
data=loads(writes(species[Symbol('SUNKERN')]))
moves=[(1,'ABSORB'),(1,'GROWTH'),(4,'PAYBACK'),(7,'INGRAIN'),(10,'MEGADRAIN'),(13,'LEECHSEED'),(16,'ASSURANCE'),(19,'WORRYSEED'),(22,'GIGADRAIN'),(25,'ENDEAVOR'),(28,'ENDURE'),(31,'DARKPULSE'),(34,'ENERGYBALL'),(37,'SEEDBOMB'),(40,'GRASSYTERRAIN')]
removed={'SUNNYDAY','SOLARBEAM','SYNTHESIS','MORNINGSUN'}
tutors=[str(x).lstrip(':') for x in data.attributes['@tutor_moves'] if str(x).lstrip(':') not in removed]
for m in ['PAYBACK','ASSURANCE','DARKPULSE','SNARL']:
 if m not in tutors:tutors.append(m)
eggs=[str(x).lstrip(':') for x in data.attributes['@egg_moves'] if str(x).lstrip(':') not in removed]
entry='With no sunrise to turn towards, its leaves droop and its shell loses its colour. It roots in the dark soil, drawing out just enough energy to endure another night.'
valid=loads((G/'Data/moves.dat').read_bytes())
for m in [m for _,m in moves]+tutors+eggs:assert Symbol(m) in valid,m
data.attributes.update({'@id':Symbol('SUNKERN_1'),'@form':1,'@pokedex_form':1,'@real_form_name':'Tidebound','@types':[Symbol('GRASS'),Symbol('DARK')],'@moves':[[lv,Symbol(m)] for lv,m in moves],'@tutor_moves':[Symbol(x) for x in tutors],'@egg_moves':[Symbol(x) for x in eggs],'@real_pokedex_entry':entry,'@color':Symbol('Brown'),'@pbs_file_suffix':'tidebound','@evolutions':[[Symbol('MOONKERN'),Symbol('Level'),14,False]]})
species[Symbol('SUNKERN_1')]=data
(G/'Data/species.dat').write_bytes(writes(species))
text='# Tidebound regional forms. Generated by Development/rebuild_regional_data.py\n[SUNKERN,1]\nFormName = Tidebound\nTypes = GRASS,DARK\nColor = Brown\nEvolutions = MOONKERN,Level,14\n'
text+='Moves = '+','.join(str(x) for pair in moves for x in pair)+'\nTutorMoves = '+','.join(tutors)+'\nEggMoves = '+','.join(eggs)+'\nPokedex = '+entry+'\n'
(G/'PBS/pokemon_forms_tidebound.txt').write_text(text,encoding='utf-8-sig')
print('Built Sunkern form 1: Grass/Dark, 15 level-up entries; original data retained.')

# Moonkern is a new species, not a Sunflora form. Reverse evolution data is needed
# by Essentials family/move inheritance; the forward rule belongs only to form 1.
moon=loads(writes(species[Symbol('SUNKERN')]))
moon_moves=[(0,'HEX'),(1,'ABSORB'),(1,'GROWTH'),(1,'ASTONISH'),(1,'SPITE'),(4,'PAYBACK'),(7,'INGRAIN'),(10,'MEGADRAIN'),(13,'LEECHSEED'),(16,'CONFUSERAY'),(19,'WORRYSEED'),(22,'GIGADRAIN'),(25,'ENDURE'),(28,'WILLOWISP'),(31,'SHADOWBALL'),(34,'ENERGYBALL'),(37,'STRENGTHSAP'),(40,'GRASSYTERRAIN'),(44,'LEAFSTORM')]
moon_tutors=sorted(set(tutors+['HEX','SHADOWBALL','WILLOWISP']))
for m in [m for _,m in moon_moves]+moon_tutors:assert Symbol(m) in valid,m
stats={'HP':65,'ATTACK':45,'DEFENSE':65,'SPEED':60,'SPECIAL_ATTACK':105,'SPECIAL_DEFENSE':100}
moon_entry='It waited for a sunrise that never came. Its seed never sprouted; only a hollow outline remains, carrying the weary longing of the plant it could not become.'
moon.attributes.update({'@id':Symbol('MOONKERN'),'@species':Symbol('MOONKERN'),'@form':0,'@pokedex_form':0,'@real_name':'Moonkern','@real_form_name':None,'@real_category':'Unbloomed','@real_pokedex_entry':moon_entry,'@types':[Symbol('GRASS'),Symbol('GHOST')],'@base_stats':{Symbol(k):v for k,v in stats.items()},'@base_exp':155,'@catch_rate':75,'@evs':{Symbol(k):(2 if k=='SPECIAL_ATTACK' else 0) for k in stats},'@moves':[[lv,Symbol(m)] for lv,m in moon_moves],'@tutor_moves':[Symbol(m) for m in moon_tutors],'@egg_moves':[],'@abilities':[Symbol('INSOMNIA'),Symbol('INFILTRATOR')],'@hidden_abilities':[Symbol('CURSEDBODY')],'@evolutions':[[Symbol('SUNKERN'),Symbol('Level'),14,True]],'@height':6,'@weight':1,'@color':Symbol('Gray'),'@flags':['DefaultForm_0'],'@pbs_file_suffix':'tidebound'})
species[Symbol('MOONKERN')]=moon
(G/'Data/species.dat').write_bytes(writes(species))
text='# Tidebound species. Generated by Development/rebuild_regional_data.py\n[MOONKERN]\nName = Moonkern\nTypes = GRASS,GHOST\nBaseStats = 65,45,65,60,105,100\nGenderRatio = Female50Percent\nGrowthRate = Parabolic\nBaseExp = 155\nEVs = SPECIAL_ATTACK,2\nCatchRate = 75\nHappiness = 50\nAbilities = INSOMNIA,INFILTRATOR\nHiddenAbilities = CURSEDBODY\n'
text+='Moves = '+','.join(str(x) for pair in moon_moves for x in pair)+'\nTutorMoves = '+','.join(moon_tutors)+'\nEggGroups = Grass\nHatchSteps = 5120\nHeight = 0.6\nWeight = 0.1\nColor = Gray\nShape = Head\nHabitat = Grassland\nCategory = Unbloomed\nPokedex = '+moon_entry+'\nGeneration = 0\nFlags = DefaultForm_0\n'
moon.attributes['@generation']=0
(G/'Data/species.dat').write_bytes(writes(species))
(G/'PBS/pokemon_tidebound.txt').write_text(text,encoding='utf-8-sig')
metrics=loads((G/'Data/species_metrics.dat').read_bytes())
mt=loads(writes(metrics[Symbol('SUNKERN')]))
mt.attributes.update({'@id':Symbol('MOONKERN'),'@species':Symbol('MOONKERN'),'@form':0,'@front_sprite':[0,10],'@back_sprite':[0,0],'@front_sprite_altitude':6,'@shadow_size':0,'@pbs_file_suffix':'tidebound'})
metrics[Symbol('MOONKERN')]=mt
(G/'Data/species_metrics.dat').write_bytes(writes(metrics))
(G/'PBS/pokemon_metrics_tidebound.txt').write_text('[MOONKERN]\nBackSprite = 0,0\nFrontSprite = 0,10\nFrontSpriteAltitude = 6\nShadowX = 0\nShadowSize = 0\n')
import shutil
shutil.copy2(G/'Audio/SE/Cries/SUNKERN.ogg',G/'Audio/SE/Cries/MOONKERN.ogg')
print('Built Moonkern, BST 440; regional Sunkern evolves at level 14. Stock evolution retained.')

import runpy
runpy.run_path(str(G/"Development/rebuild_moonflora_data.py"))
runpy.run_path(str(G/"Development/rebuild_wurmple_data.py"))
runpy.run_path(str(G/"Development/rebuild_lapras_data.py"))
runpy.run_path(str(G/"Development/rebuild_whyduck_data.py"))
