"""Build gray Normal/Dark regional snakes and replace all Poison learnset entries.

Ordinary species remain intact. Regional Ekans evolves into regional Arbok at 22.
Run independently, or through rebuild_regional_data.py.
"""
from pathlib import Path
import runpy
from rubymarshal.reader import loads
from rubymarshal.writer import writes
from rubymarshal.classes import Symbol as S

G = Path(__file__).resolve().parent.parent
species = loads((G / 'Data/species.dat').read_bytes())
moves = loads((G / 'Data/moves.dat').read_bytes())
REPLACEMENTS = {
    'POISONSTING': 'PURSUIT',
    'ACID': 'SNARL',
    'ACIDSPRAY': 'ASSURANCE',
    'SLUDGEBOMB': 'DARKPULSE',
    'GASTROACID': 'TAUNT',
    'BELCH': 'FOULPLAY',
    'COIL': 'HONECLAWS',
    'GUNKSHOT': 'THROATCHOP',
    'POISONJAB': 'CRUNCH',
    'SLUDGEWAVE': 'DARKPULSE',
    'VENOSHOCK': 'PAYBACK',
    'POISONFANG': 'JAWLOCK',
    'POISONTAIL': 'NIGHTSLASH',
}

def replace(move):
    if moves[move].attributes['@type'] != S('POISON'):
        return move
    replacement = S(REPLACEMENTS[str(move).lstrip(':')])
    assert moves[replacement].attributes['@type'] == S('DARK')
    return replacement

def unique(seq):
    return list(dict.fromkeys(seq))

pbs = ['# Gray regional snakes. Generated by Development/rebuild_snake_data.py.']
for name in ('EKANS', 'ARBOK'):
    form = loads(writes(species[S(name)]))
    attrs = form.attributes
    attrs.update({
        '@id': S(name + '_1'), '@species': S(name), '@form': 1,
        '@pokedex_form': 1, '@real_form_name': 'Tidebound',
        '@types': [S('NORMAL'), S('DARK')], '@color': S('Gray'),
        '@pbs_file_suffix': 'tidebound_snakes',
        '@moves': [[level, replace(move)] for level, move in attrs['@moves']],
        '@tutor_moves': unique(replace(move) for move in attrs['@tutor_moves']),
        '@egg_moves': unique(replace(move) for move in attrs['@egg_moves']),
    })
    # Retain the native forward/reverse evolution data. Both species have form 1,
    # so Pokemon#species= preserves that form; no DefaultForm_0 flag is added.
    species[S(name + '_1')] = form
    flatten = lambda seq: ','.join(str(x).lstrip(':') for x in seq)
    pbs += ['', '[' + name + ',1]', 'FormName = Tidebound',
            'Types = NORMAL,DARK', 'Color = Gray',
            'Moves = ' + flatten(x for row in attrs['@moves'] for x in row),
            'TutorMoves = ' + flatten(attrs['@tutor_moves'])]
    if attrs['@egg_moves']:
        pbs.append('EggMoves = ' + flatten(attrs['@egg_moves']))
    if name == 'EKANS':
        pbs.append('Evolutions = ARBOK,Level,22')

(G / 'Data/species.dat').write_bytes(writes(species))
(G / 'PBS/pokemon_forms_tidebound_snakes.txt').write_text('\n'.join(pbs) + '\n', encoding='utf-8-sig')
runpy.run_path(str(G / 'Development/Art/Snakes/recolour.py'))
print('Built Normal/Dark Ekans and Arbok; all Poison moves replaced, base stats retained.')
