"""Coastal species, forms and sprite placement in PBS terminology."""

SPECIES = {
    "LAPRAS_1": {
        "inherit": "LAPRAS",
        "file": "pokemon_forms_tidebound_lapras",
        "fields": {"FormName": "Tidebound", "Types": ("WATER", "GHOST"), "Color": "White"},
    },
    "PSYDUCK_1": {
        "inherit": "PSYDUCK",
        "file": "pokemon_forms_tidebound_psyduck",
        "fields": {
            "FormName": "Tidebound",
            "Types": ("WATER", "PSYCHIC"),
            "Evolutions": (("WHYDUCK", "Level", 16),),
        },
    },
    "WHYDUCK": {
        "inherit": "PSYDUCK",
        "file": "pokemon_whyduck",
        "fields": {
            "Name": "Whyduck",
            "Types": ("WATER", "PSYCHIC"),
            "BaseStats": (75, 55, 70, 75, 130, 115),
            "GenderRatio": "Female50Percent",
            "GrowthRate": "Medium",
            "BaseExp": 190,
            "EVs": (("SPECIAL_ATTACK", 2),),
            "CatchRate": 75,
            "Happiness": 70,
            "Abilities": ("OWNTEMPO", "CLOUDNINE"),
            "HiddenAbilities": ("INNERFOCUS",),
            "Moves": (
                (0, "PSYCHIC"),
                (1, "AQUAJET"),
                (1, "WATERGUN"),
                (1, "CONFUSION"),
                (1, "TAILWHIP"),
                (9, "PSYBEAM"),
                (13, "WATERPULSE"),
                (17, "DISABLE"),
                (21, "MIST"),
                (25, "PSYCHUP"),
                (29, "AQUARING"),
                (35, "CALMMIND"),
                (40, "PSYSHOCK"),
                (44, "BRINE"),
                (48, "FUTURESIGHT"),
                (52, "HYDROPUMP"),
                (56, "PSYCHICTERRAIN"),
                (60, "RECOVER"),
                (65, "STOREDPOWER"),
            ),
            "TutorMoves": (
                "PSYCHIC",
                "PSYSHOCK",
                "FUTURESIGHT",
                "CALMMIND",
                "LIGHTSCREEN",
                "REFLECT",
                "TRICKROOM",
                "PSYCHICTERRAIN",
                "SURF",
                "SCALD",
                "ICEBEAM",
                "BLIZZARD",
                "RAINDANCE",
                "PROTECT",
                "REST",
                "DIVE",
                "ENCORE",
                "AMNESIA",
                "SUBSTITUTE",
                "WATERPULSE",
                "WONDERROOM",
            ),
            "EggGroups": ("Water1", "Field"),
            "HatchSteps": 5120,
            "Height": 1.1,
            "Weight": 26.0,
            "Color": "Yellow",
            "Shape": "BipedalTail",
            "Habitat": "WatersEdge",
            "Category": "Still Mind",
            "Pokedex": "Its headaches ceased when the folds on its head opened. It "
            "stands quietly by the tide for hours, as if considering a "
            "question it cannot ask.",
            "Generation": 0,
            "Flags": ("DefaultForm_0",),
            "EggMoves": (),
            "WildItemCommon": (),
            "WildItemUncommon": (),
            "WildItemRare": (),
        },
    },
    "EKANS_1": {
        "inherit": "EKANS",
        "file": "pokemon_forms_tidebound_snakes",
        "fields": {
            "FormName": "Tidebound",
            "Types": ("NORMAL", "DARK"),
            "Color": "Gray",
            "Moves": (
                (1, "WRAP"),
                (1, "LEER"),
                (4, "PURSUIT"),
                (9, "BITE"),
                (12, "GLARE"),
                (17, "SCREECH"),
                (20, "SNARL"),
                (25, "STOCKPILE"),
                (25, "SWALLOW"),
                (25, "SPITUP"),
                (28, "ASSURANCE"),
                (33, "DARKPULSE"),
                (36, "TAUNT"),
                (38, "FOULPLAY"),
                (41, "HAZE"),
                (44, "HONECLAWS"),
                (49, "THROATCHOP"),
            ),
            "TutorMoves": (
                "AQUATAIL",
                "ATTRACT",
                "BIND",
                "BODYSLAM",
                "BRUTALSWING",
                "BULLDOZE",
                "CAPTIVATE",
                "CONFIDE",
                "DARKPULSE",
                "DIG",
                "DOUBLEEDGE",
                "DOUBLETEAM",
                "EARTHQUAKE",
                "ENDURE",
                "FACADE",
                "FRUSTRATION",
                "TAUNT",
                "GIGADRAIN",
                "THROATCHOP",
                "HEADBUTT",
                "HIDDENPOWER",
                "INFESTATION",
                "IRONTAIL",
                "MIMIC",
                "NATURALGIFT",
                "PAYBACK",
                "CRUNCH",
                "PROTECT",
                "RAINDANCE",
                "REST",
                "RETURN",
                "ROCKSLIDE",
                "ROCKTOMB",
                "ROUND",
                "SECRETPOWER",
                "SEEDBOMB",
                "SLEEPTALK",
                "SNATCH",
                "SNORE",
                "SPITE",
                "STRENGTH",
                "SUBSTITUTE",
                "SUNNYDAY",
                "SWAGGER",
                "THIEF",
                "TORMENT",
            ),
            "EggMoves": (
                "BEATUP",
                "DISABLE",
                "JAWLOCK",
                "NIGHTSLASH",
                "SCARYFACE",
                "SLAM",
                "SPITE",
                "SUCKERPUNCH",
                "SWITCHEROO",
            ),
            "Evolutions": (("ARBOK", "Level", 22),),
        },
    },
    "ARBOK_1": {
        "inherit": "ARBOK",
        "file": "pokemon_forms_tidebound_snakes",
        "fields": {
            "FormName": "Tidebound",
            "Types": ("NORMAL", "DARK"),
            "Color": "Gray",
            "Moves": (
                (0, "CRUNCH"),
                (1, "ICEFANG"),
                (1, "THUNDERFANG"),
                (1, "FIREFANG"),
                (1, "WRAP"),
                (1, "LEER"),
                (1, "PURSUIT"),
                (1, "BITE"),
                (4, "PURSUIT"),
                (9, "BITE"),
                (12, "GLARE"),
                (17, "SCREECH"),
                (20, "SNARL"),
                (27, "STOCKPILE"),
                (27, "SWALLOW"),
                (27, "SPITUP"),
                (32, "ASSURANCE"),
                (39, "DARKPULSE"),
                (44, "TAUNT"),
                (48, "FOULPLAY"),
                (51, "HAZE"),
                (56, "HONECLAWS"),
                (63, "THROATCHOP"),
            ),
            "TutorMoves": (
                "AQUATAIL",
                "ATTRACT",
                "BIND",
                "BODYSLAM",
                "BRUTALSWING",
                "BULLDOZE",
                "CAPTIVATE",
                "CONFIDE",
                "DARKPULSE",
                "DIG",
                "DOUBLEEDGE",
                "DOUBLETEAM",
                "DRAGONTAIL",
                "EARTHQUAKE",
                "ENDURE",
                "FACADE",
                "FRUSTRATION",
                "TAUNT",
                "GIGADRAIN",
                "GIGAIMPACT",
                "THROATCHOP",
                "HEADBUTT",
                "HIDDENPOWER",
                "HYPERBEAM",
                "INFESTATION",
                "IRONTAIL",
                "MIMIC",
                "NATURALGIFT",
                "PAYBACK",
                "CRUNCH",
                "PROTECT",
                "RAINDANCE",
                "REST",
                "RETURN",
                "ROCKSLIDE",
                "ROCKTOMB",
                "ROUND",
                "SECRETPOWER",
                "SEEDBOMB",
                "SLEEPTALK",
                "SNATCH",
                "SNORE",
                "SPITE",
                "STOMPINGTANTRUM",
                "STRENGTH",
                "SUBSTITUTE",
                "SUNNYDAY",
                "SWAGGER",
                "THIEF",
                "TORMENT",
            ),
        },
    },
}

METRICS = {
    "WHYDUCK": {
        "inherit": "PSYDUCK",
        "file": "pokemon_metrics_whyduck",
        "fields": {"BackSprite": (0, 5), "FrontSprite": (1, 13), "ShadowX": 0, "ShadowSize": 2},
    }
}
