"""Insects species, forms and sprite placement in PBS terminology."""

SPECIES = {
    "WURMPLE_1": {
        "inherit": "WURMPLE",
        "file": "pokemon_forms_tidebound_wurmple",
        "fields": {
            "FormName": "Tidebound",
            "Types": ("BUG", "ICE"),
            "Color": "Blue",
            "Evolutions": (("GLACIVERM", "Silcoon", 10), ("FROSTCOON", "Cascoon", 10)),
        },
    },
    "GLACIVERM": {
        "inherit": "WURMPLE",
        "file": "pokemon_glaciverm",
        "fields": {
            "Name": "Glaciverm",
            "Types": ("ICE", "BUG"),
            "BaseStats": (75, 105, 110, 40, 40, 65),
            "GenderRatio": "Female50Percent",
            "GrowthRate": "Medium",
            "BaseExp": 145,
            "EVs": (("DEFENSE", 2),),
            "CatchRate": 75,
            "Happiness": 50,
            "Abilities": ("TECHNICIAN",),
            "Moves": (
                (0, "BUGBITE"),
                (1, "TACKLE"),
                (1, "STRINGSHOT"),
                (1, "POWDERSNOW"),
                (10, "ICESHARD"),
                (13, "BIND"),
                (16, "ICEFANG"),
                (20, "FIRSTIMPRESSION"),
                (24, "COIL"),
                (28, "PINMISSILE"),
                (32, "IRONDEFENSE"),
                (36, "ICICLESPEAR"),
                (40, "XSCISSOR"),
                (44, "ICICLECRASH"),
                (48, "LUNGE"),
            ),
            "TutorMoves": (
                "BUGBITE",
                "ICEFANG",
                "IRONDEFENSE",
                "PROTECT",
                "ENDURE",
                "FACADE",
                "SUBSTITUTE",
                "SLEEPTALK",
                "SNORE",
                "ICEBEAM",
                "BLIZZARD",
                "XSCISSOR",
            ),
            "EggGroups": ("Bug",),
            "HatchSteps": 3840,
            "Height": 1.8,
            "Weight": 24.0,
            "Color": "Blue",
            "Shape": "Serpentine",
            "Habitat": "Forest",
            "Category": "Frost Coil",
            "Pokedex": "It coils its long body beneath roots. Overlapping plates of "
            "frozen chitin protect it while it waits to strike at "
            "anything that steps too close.",
            "Generation": 0,
            "Flags": ("DefaultForm_0",),
            "EggMoves": (),
            "HiddenAbilities": (),
            "WildItemCommon": (),
            "WildItemUncommon": (),
            "WildItemRare": (),
        },
    },
    "FROSTCOON": {
        "inherit": "SILCOON",
        "file": "pokemon_glaciverm",
        "fields": {
            "Name": "Frostcoon",
            "Types": ("BUG", "ICE"),
            "BaseStats": (65, 35, 95, 15, 55, 85),
            "GenderRatio": "Female50Percent",
            "GrowthRate": "Medium",
            "BaseExp": 95,
            "EVs": (("DEFENSE", 2),),
            "CatchRate": 120,
            "Happiness": 50,
            "Abilities": ("SHELLARMOR",),
            "Moves": (
                (0, "SPIKES"),
                (1, "HARDEN"),
                (1, "STRINGSHOT"),
                (10, "WISH"),
                (13, "STUNSPORE"),
                (16, "RAINDANCE"),
                (19, "PROTECT"),
                (22, "LIFEDEW"),
                (25, "STICKYWEB"),
                (28, "SLEEPPOWDER"),
                (31, "HAIL"),
                (34, "AURORAVEIL"),
                (38, "REFLECT"),
                (42, "LIGHTSCREEN"),
                (46, "SAFEGUARD"),
                (50, "BATONPASS"),
                (54, "WIDEGUARD"),
            ),
            "TutorMoves": (
                "PROTECT",
                "ENDURE",
                "SUBSTITUTE",
                "SAFEGUARD",
                "LIGHTSCREEN",
                "REFLECT",
                "HAIL",
                "RAINDANCE",
                "IRONDEFENSE",
                "HELPINGHAND",
            ),
            "EggGroups": ("Bug",),
            "HatchSteps": 3840,
            "Height": 0.7,
            "Weight": 12.0,
            "Color": "Blue",
            "Shape": "Head",
            "Habitat": "Forest",
            "Category": "Frozen Silk",
            "Pokedex": "It seals itself in silk glazed with frost. Even when its "
            "shell lies perfectly still, a faint scratching can be heard "
            "from within.",
            "Generation": 0,
            "Flags": ("DefaultForm_0",),
            "Evolutions": (("NIVALORA", "Level", 55),),
            "EggMoves": (),
            "HiddenAbilities": (),
            "WildItemCommon": (),
            "WildItemUncommon": (),
            "WildItemRare": (),
        },
    },
    "NIVALORA": {
        "inherit": "FROSTCOON",
        "file": "pokemon_nivalora",
        "fields": {
            "Name": "Nivalora",
            "Types": ("ICE", "DRAGON"),
            "BaseStats": (100, 45, 65, 145, 130, 115),
            "GenderRatio": "Female50Percent",
            "GrowthRate": "Medium",
            "BaseExp": 300,
            "EVs": (("SPEED", 3),),
            "CatchRate": 45,
            "Happiness": 70,
            "Abilities": ("SHIELDDUST",),
            "Moves": (
                (0, "DRAGONBREATH"),
                (1, "GUST"),
                (1, "POWDERSNOW"),
                (1, "HARDEN"),
                (1, "STRINGSHOT"),
                (10, "WISH"),
                (13, "STUNSPORE"),
                (16, "RAINDANCE"),
                (19, "PROTECT"),
                (22, "LIFEDEW"),
                (25, "STICKYWEB"),
                (28, "SLEEPPOWDER"),
                (31, "HAIL"),
                (34, "AURORAVEIL"),
                (38, "REFLECT"),
                (42, "LIGHTSCREEN"),
                (46, "SAFEGUARD"),
                (50, "BATONPASS"),
                (54, "WIDEGUARD"),
                (55, "ICEBEAM"),
                (58, "DRAGONDANCE"),
                (61, "ROOST"),
                (64, "DRAGONPULSE"),
                (68, "BLIZZARD"),
                (72, "QUIVERDANCE"),
                (76, "TAILWIND"),
                (80, "MIST"),
            ),
            "TutorMoves": (
                "PROTECT",
                "ENDURE",
                "SUBSTITUTE",
                "SAFEGUARD",
                "LIGHTSCREEN",
                "REFLECT",
                "HAIL",
                "RAINDANCE",
                "HELPINGHAND",
                "ICEBEAM",
                "BLIZZARD",
                "ICYWIND",
                "DRAGONPULSE",
                "DRACOMETEOR",
                "ROOST",
                "TAILWIND",
                "AERIALACE",
                "ACROBATICS",
            ),
            "EggGroups": ("Bug", "Dragon"),
            "HatchSteps": 3840,
            "Height": 2.4,
            "Weight": 22.0,
            "Color": "White",
            "Shape": "MultiWinged",
            "Habitat": "Forest",
            "Category": "Kindly Wings",
            "Pokedex": "Rarely seen, it shelters lost travelers beneath its "
            "frost-white wings. Its gentle scales lull frightened "
            "creatures to sleep, and it waits beside them until they wake.",
            "Generation": 0,
            "Flags": ("DefaultForm_0",),
            "EggMoves": (),
            "HiddenAbilities": (),
            "WildItemCommon": (),
            "WildItemUncommon": (),
            "WildItemRare": (),
        },
    },
}

METRICS = {
    "GLACIVERM": {
        "inherit": "WURMPLE",
        "file": "pokemon_metrics_glaciverm",
        "fields": {
            "BackSprite": (-1, 0),
            "FrontSprite": (-2, 18),
            "FrontSpriteAltitude": 0,
            "ShadowX": 0,
            "ShadowSize": 1,
        },
    },
    "FROSTCOON": {
        "inherit": "SILCOON",
        "file": "pokemon_metrics_glaciverm",
        "fields": {
            "BackSprite": (-2, 0),
            "FrontSprite": (0, 24),
            "FrontSpriteAltitude": 0,
            "ShadowX": 0,
            "ShadowSize": 2,
        },
    },
    "NIVALORA": {
        "inherit": "VENOMOTH",
        "file": "pokemon_metrics_nivalora",
        "fields": {
            "BackSprite": (0, 0),
            "FrontSprite": (0, 4),
            "FrontSpriteAltitude": 8,
            "ShadowX": 0,
            "ShadowSize": 1,
        },
    },
}

CRIES = {"GLACIVERM": "WURMPLE", "FROSTCOON": "SILCOON", "NIVALORA": "ARTICUNO"}
