"""Plants species, forms and sprite placement in PBS terminology."""

SPECIES = {
    "SUNKERN_1": {
        "inherit": "SUNKERN",
        "file": "pokemon_forms_tidebound",
        "fields": {
            "FormName": "Tidebound",
            "Types": ("GRASS", "DARK"),
            "Color": "Brown",
            "Evolutions": (("MOONKERN", "Level", 14),),
            "Moves": (
                (1, "ABSORB"),
                (1, "GROWTH"),
                (4, "PAYBACK"),
                (7, "INGRAIN"),
                (10, "MEGADRAIN"),
                (13, "LEECHSEED"),
                (16, "ASSURANCE"),
                (19, "WORRYSEED"),
                (22, "GIGADRAIN"),
                (25, "ENDEAVOR"),
                (28, "ENDURE"),
                (31, "DARKPULSE"),
                (34, "ENERGYBALL"),
                (37, "SEEDBOMB"),
                (40, "GRASSYTERRAIN"),
            ),
            "TutorMoves": (
                "AFTERYOU",
                "ATTRACT",
                "BULLETSEED",
                "CAPTIVATE",
                "CONFIDE",
                "CUT",
                "DOUBLEEDGE",
                "DOUBLETEAM",
                "EARTHPOWER",
                "ENDEAVOR",
                "ENDURE",
                "ENERGYBALL",
                "FACADE",
                "FLASH",
                "FRUSTRATION",
                "GIGADRAIN",
                "GRASSKNOT",
                "HELPINGHAND",
                "HIDDENPOWER",
                "LIGHTSCREEN",
                "MIMIC",
                "NATURALGIFT",
                "NATUREPOWER",
                "PROTECT",
                "REST",
                "RETURN",
                "ROUND",
                "SAFEGUARD",
                "SECRETPOWER",
                "SEEDBOMB",
                "SLEEPTALK",
                "SLUDGEBOMB",
                "SNORE",
                "SUBSTITUTE",
                "SWAGGER",
                "UPROAR",
                "WORRYSEED",
                "PAYBACK",
                "ASSURANCE",
                "DARKPULSE",
                "SNARL",
            ),
            "EggMoves": (
                "CURSE",
                "ENCORE",
                "GRASSYTERRAIN",
                "HELPINGHAND",
                "INGRAIN",
                "LEECHSEED",
                "NATUREPOWER",
                "SWEETSCENT",
            ),
            "Pokedex": "With no sunrise to turn towards, its leaves droop and its "
            "shell loses its colour. It roots in the dark soil, drawing "
            "out just enough energy to endure another night.",
        },
    },
    "MOONKERN": {
        "inherit": "SUNKERN",
        "file": "pokemon_tidebound",
        "fields": {
            "Name": "Moonkern",
            "Types": ("GRASS", "GHOST"),
            "BaseStats": (65, 45, 65, 60, 105, 100),
            "GenderRatio": "Female50Percent",
            "GrowthRate": "Parabolic",
            "BaseExp": 155,
            "EVs": (("SPECIAL_ATTACK", 2),),
            "CatchRate": 75,
            "Happiness": 50,
            "Abilities": ("INSOMNIA", "INFILTRATOR"),
            "HiddenAbilities": ("CURSEDBODY",),
            "Moves": (
                (0, "HEX"),
                (1, "ABSORB"),
                (1, "GROWTH"),
                (1, "ASTONISH"),
                (1, "SPITE"),
                (4, "PAYBACK"),
                (7, "INGRAIN"),
                (10, "MEGADRAIN"),
                (13, "LEECHSEED"),
                (16, "CONFUSERAY"),
                (19, "WORRYSEED"),
                (22, "GIGADRAIN"),
                (25, "ENDURE"),
                (28, "WILLOWISP"),
                (31, "SHADOWBALL"),
                (34, "ENERGYBALL"),
                (37, "STRENGTHSAP"),
                (40, "GRASSYTERRAIN"),
                (44, "LEAFSTORM"),
            ),
            "TutorMoves": (
                "AFTERYOU",
                "ASSURANCE",
                "ATTRACT",
                "BULLETSEED",
                "CAPTIVATE",
                "CONFIDE",
                "CUT",
                "DARKPULSE",
                "DOUBLEEDGE",
                "DOUBLETEAM",
                "EARTHPOWER",
                "ENDEAVOR",
                "ENDURE",
                "ENERGYBALL",
                "FACADE",
                "FLASH",
                "FRUSTRATION",
                "GIGADRAIN",
                "GRASSKNOT",
                "HELPINGHAND",
                "HEX",
                "HIDDENPOWER",
                "LIGHTSCREEN",
                "MIMIC",
                "NATURALGIFT",
                "NATUREPOWER",
                "PAYBACK",
                "PROTECT",
                "REST",
                "RETURN",
                "ROUND",
                "SAFEGUARD",
                "SECRETPOWER",
                "SEEDBOMB",
                "SHADOWBALL",
                "SLEEPTALK",
                "SLUDGEBOMB",
                "SNARL",
                "SNORE",
                "SUBSTITUTE",
                "SWAGGER",
                "UPROAR",
                "WILLOWISP",
                "WORRYSEED",
            ),
            "EggGroups": ("Grass",),
            "HatchSteps": 5120,
            "Height": 0.6,
            "Weight": 0.1,
            "Color": "Gray",
            "Shape": "Head",
            "Habitat": "Grassland",
            "Category": "Unbloomed",
            "Pokedex": "It waited for a sunrise that never came. Its seed never "
            "sprouted; only a hollow outline remains, carrying the weary "
            "longing of the plant it could not become.",
            "Generation": 0,
            "Flags": ("DefaultForm_0",),
            "Evolutions": (("MOONFLORA", "Level", 20),),
            "EggMoves": (),
            "WildItemCommon": (),
            "WildItemUncommon": (),
            "WildItemRare": (),
        },
    },
    "MOONFLORA": {
        "inherit": "MOONKERN",
        "file": "pokemon_tidebound",
        "fields": {
            "Name": "Moonflora",
            "Types": ("GRASS", "GHOST"),
            "BaseStats": (75, 50, 80, 60, 115, 110),
            "GenderRatio": "Female50Percent",
            "GrowthRate": "Parabolic",
            "BaseExp": 210,
            "EVs": (("SPECIAL_ATTACK", 3),),
            "CatchRate": 45,
            "Happiness": 50,
            "Abilities": ("INSOMNIA", "INFILTRATOR"),
            "HiddenAbilities": ("CURSEDBODY",),
            "Moves": (
                (0, "SHADOWBALL"),
                (1, "ABSORB"),
                (1, "ASTONISH"),
                (1, "GROWTH"),
                (1, "HEX"),
                (1, "SPITE"),
                (4, "PAYBACK"),
                (7, "INGRAIN"),
                (10, "MEGADRAIN"),
                (13, "LEECHSEED"),
                (16, "CONFUSERAY"),
                (19, "WORRYSEED"),
                (22, "GIGADRAIN"),
                (23, "WILLOWISP"),
                (25, "ENDURE"),
                (31, "NASTYPLOT"),
                (34, "ENERGYBALL"),
                (37, "STRENGTHSAP"),
                (40, "GRASSYTERRAIN"),
                (44, "LEAFSTORM"),
            ),
            "TutorMoves": (
                "AFTERYOU",
                "ASSURANCE",
                "ATTRACT",
                "BULLETSEED",
                "CAPTIVATE",
                "CONFIDE",
                "CUT",
                "DARKPULSE",
                "DOUBLEEDGE",
                "DOUBLETEAM",
                "EARTHPOWER",
                "ENDEAVOR",
                "ENDURE",
                "ENERGYBALL",
                "FACADE",
                "FLASH",
                "FRUSTRATION",
                "GIGADRAIN",
                "GRASSKNOT",
                "HELPINGHAND",
                "HEX",
                "HIDDENPOWER",
                "LIGHTSCREEN",
                "MIMIC",
                "NATURALGIFT",
                "NATUREPOWER",
                "PAYBACK",
                "PROTECT",
                "REST",
                "RETURN",
                "ROUND",
                "SAFEGUARD",
                "SECRETPOWER",
                "SEEDBOMB",
                "SHADOWBALL",
                "SLEEPTALK",
                "SLUDGEBOMB",
                "SNARL",
                "SNORE",
                "SUBSTITUTE",
                "SWAGGER",
                "UPROAR",
                "WILLOWISP",
                "WORRYSEED",
            ),
            "EggGroups": ("Grass",),
            "HatchSteps": 5120,
            "Height": 1.1,
            "Weight": 0.1,
            "Color": "Gray",
            "Shape": "Bipedal",
            "Habitat": "Grassland",
            "Category": "Phantom Bloom",
            "Pokedex": "The flower it longed to become appears only as a spirit. Its "
            "hollow face turns towards an absent sun, weary eyes burning "
            "with a quiet resentment.",
            "Generation": 0,
            "Flags": ("DefaultForm_0",),
            "EggMoves": (),
            "WildItemCommon": (),
            "WildItemUncommon": (),
            "WildItemRare": (),
        },
    },
}

METRICS = {
    "MOONKERN": {
        "inherit": "SUNKERN",
        "file": "pokemon_metrics_tidebound",
        "fields": {
            "BackSprite": (0, 0),
            "FrontSprite": (0, 10),
            "FrontSpriteAltitude": 6,
            "ShadowX": 0,
            "ShadowSize": 0,
        },
    },
    "MOONFLORA": {
        "inherit": "MOONKERN",
        "file": "pokemon_metrics_tidebound",
        "fields": {
            "BackSprite": (0, 0),
            "FrontSprite": (0, 18),
            "FrontSpriteAltitude": 6,
            "ShadowX": 0,
            "ShadowSize": 0,
        },
    },
}

CRIES = {"MOONKERN": "SUNKERN", "MOONFLORA": "SUNFLORA"}
