root = File.expand_path("..", __dir__)
load File.join(__dir__, "001_Support.rb")
load File.join(root, "src/tidebound/domain/state.rb")
load File.join(root, "src/tidebound/engine/battles.rb")
load File.join(__dir__, "002_CoreTests.rb")
load File.join(__dir__, "003_AdapterTests.rb")
