"""Map-qualified actor identities and explicit runtime roles, independent of labels."""

from ..art import props
from ..files import ruby

# Roles select concrete consumers in world/actors.rb and presentation modules.
ROLES = {
    "npc",
    "house",
    "room",
    "outside_dog",
    "spirit",
    "wood_bird",
    "neighbor_wild",
    "shore_duck",
    "dock_fighter",
    "keys",
    "crate",
    "fire",
    "main_lamp",
    "lamp",
    "lapras",
    "coast_lamp",
    "berry",
    "prop",
}


def validate_actor(info):
    role = info.get("role", "")
    if role and role not in ROLES:
        raise ValueError(f"Unknown actor role: {role}")
    if role in (
        "house",
        "room",
        "outside_dog",
        "wood_bird",
        "neighbor_wild",
        "shore_duck",
        "dock_fighter",
    ) and not info.get("species"):
        raise ValueError(f"Actor role {role} requires a species")
    if role == "spirit" and (type(info.get("index")) is not int or info["index"] < 0):
        raise ValueError("Spirit actor requires a nonnegative soul index")
    if role == "neighbor_wild" and not info.get("state"):
        raise ValueError("Neighbor wild actor requires its quest state key")
    if role == "prop" and not info.get("asset"):
        raise ValueError("Static prop requires an asset name")
    if info.get("cue") and info["cue"] not in ("north", "south", "east", "west"):
        raise ValueError(f"Unknown threshold direction: {info['cue']}")


def collect_actors(maps):
    actors, settings = {}, {}
    for area in maps:
        settings[area.id] = area.actor_settings
        for event_id, info in area.actor_settings.items():
            validate_actor(info)
            if event_id not in area.events:
                raise ValueError(f"Map {area.id}: actor refers to missing event {event_id}")
            key = info.get("key")
            if not key:
                continue
            if key in actors:
                raise ValueError(f"Duplicate actor identity: {key}")
            actors[key] = {"map": area.id, "event": event_id}
    return actors, settings


def write_registry(root, maps):
    actors, settings = collect_actors(maps)
    asset_events = [
        (mid, eid, info["asset"])
        for mid, events in settings.items()
        for eid, info in events.items()
        if info.get("asset")
    ]
    if asset_events:
        assets = props.load(root)
        for map_id, event_id, asset in asset_events:
            if asset not in assets:
                raise ValueError(f"Map {map_id} event {event_id}: unknown prop asset {asset}")
    lines = ["# Generated by the map compiler.", "module Tidebound", "  module World"]
    for name, records in [
        ("MAPS", {m.key: m.id for m in maps}),
        ("ACTORS", actors),
        ("ENTRANCES", {m.id: m.definition.entrances for m in maps}),
    ]:
        lines.append(f"    {name} = {{")
        lines.extend(
            f"      {str(key) + (':' if isinstance(key, str) else ' =>')} {ruby(value)},"
            for key, value in records.items()
        )
        lines.append("    }.freeze")
    lines.append("    ACTOR_SETTINGS = {")
    for map_id, events in settings.items():
        lines.append(f"      {map_id} => {{")
        lines.extend(
            f"        {event_id} => {ruby(info)}.freeze," for event_id, info in events.items()
        )
        lines.append("      }.freeze,")
    lines.append("    }.freeze")
    lines.append("    MAP_SETTINGS = {")
    for definition in (m.definition for m in maps):
        values = ", ".join(
            f"{key}: {ruby(value)}" for key, value in definition.runtime_settings().items()
        )
        lines.append(f"      {definition.id} => {{{values}}},")
    lines.append("    }.freeze")
    lines += ["  end", "end", ""]
    (root / "src/generated/world_registry.rb").write_text("\n".join(lines))
