"""Names shared by map authoring and Ruby world operations."""

import json

from .definitions import DEFINITIONS

MAPS = {name: definition.id for name, definition in DEFINITIONS.items()}
MAP_NAMES = {value: key for key, value in MAPS.items()}
ACTORS = {
    "mother": "Mother",
    "mother_visiting": "Mother visiting",
    "mother_at_vault": "Mother at vault",
    "house_natu": "House:NATU",
    "house_makuhita": "House:MAKUHITA",
    "house_poochyena": "House:POOCHYENA",
    "crate": "Crate",
    "pookie_outside": "Pookie outside",
    "oil_seller": "Oil seller",
    "seller_outside": "Seller outside",
    "seller_at_home": "Seller at home",
    "seller_at_vault": "Seller at vault",
    "road_thief": "Road thief",
    "running_thief": "Running thief",
    "robbery_youth_one": "Robbery youth one",
    "robbery_youth_two": "Robbery youth two",
    "necklace_thief": "Necklace thief",
}


def write_registry(root, maps):
    if {area.id for area in maps} != set(MAPS.values()):
        raise ValueError("Authored maps and world registry disagree")
    events = {str(event.attributes["@name"]) for area in maps for event in area.events.values()}
    missing = set(ACTORS.values()) - events
    if missing:
        raise ValueError("Missing named world actors: " + ", ".join(sorted(missing)))
    lines = ["# Generated by the map compiler.", "module Tidebound", "  module World"]
    for name, records in [("MAPS", MAPS), ("ACTORS", ACTORS)]:
        lines.append(f"    {name} = {{")
        lines.extend(f"      {key}: {json.dumps(value)}," for key, value in records.items())
        lines.append("    }.freeze")
    lines.append("    MAP_SETTINGS = {")
    for definition in DEFINITIONS.values():
        settings = ", ".join(
            f"{key}: {json.dumps(value)}" for key, value in definition.runtime_settings().items()
        )
        lines.append(f"      {definition.id} => {{{settings}}},")
    lines.append("    }.freeze")
    lines += ["  end", "end", ""]
    (root / "src/generated/world_registry.rb").write_text("\n".join(lines))
