"""Bake static dock props and source-glass masks for the runtime sprites."""

from PIL import Image, ImageDraw
from rubymarshal.reader import loads

from ..files import save_png
from .registry import ruby


def window_mask(atlas, tile):
    if tile < 384:
        return None
    x, y = (tile - 384) % 8, (tile - 384) // 8
    lighthouse = x == 6 and y in (447, 448)
    if not (
        (y == 230 and x in (2, 3))
        or (y == 232 and x == 0)
        or (y == 231 and x in (6, 7))
        or (y == 233 and x in (4, 5, 6))
        or (y == 226 and x == 5)
        or lighthouse
    ):
        return None
    mask = Image.new("RGBA", (32, 32))
    for py in range(32):
        for px in range(32):
            red, green, blue, alpha = atlas.getpixel((x * 32 + px, y * 32 + py))
            glass = (
                (red, green, blue) == (39, 47, 87)
                if lighthouse
                else alpha > 0 and blue >= 180 and green > red + 25 and blue > green + 25
            )
            if glass:
                mask.putpixel(
                    (px, py), (255, 218, 145, 235) if green > 165 else (234, 167, 79, 225)
                )
    return mask


def window_lights(paths, maps):
    tilesets = loads((paths.game / "Data/Tilesets.rxdata").read_bytes())
    masks, indices, placements = [], {}, {}
    for area in maps:
        if area.id not in (102, 108, 112):
            continue
        tileset = tilesets[area.tileset].attributes["@tileset_name"]
        with Image.open(paths.game / "Graphics/Tilesets" / f"{tileset}.png") as source:
            atlas = source.convert("RGBA")
        tiles = set(tile for row in area.layers[1] for tile in row)
        tile_masks = {tile: window_mask(atlas, tile) for tile in tiles}
        panes = []
        for y, row in enumerate(area.layers[1]):
            for x, tile in enumerate(row):
                mask = tile_masks[tile]
                if mask is None:
                    continue
                pixels = mask.tobytes()
                if pixels not in indices:
                    indices[pixels] = len(masks)
                    masks.append(mask)
                panes.append([x, y, indices[pixels]])
        placements[area.id] = panes
    sheet = Image.new("RGBA", (32 * max(1, len(masks)), 32))
    for index, mask in enumerate(masks):
        sheet.paste(mask, (index * 32, 0))
    save_png(sheet, paths.game / "Graphics/Pictures/Tidebound/window_panes.png")
    (paths.root / "src/generated/window_lights.rb").write_text(
        "# Generated by maps/scenery.py.\nmodule Tidebound::Presentation\n"
        + "  WINDOW_LIGHTS = "
        + ruby(placements)
        + ".freeze\nend\n"
    )


def dock_props(game):
    wood, dark, rope = (125, 96, 68, 255), (52, 57, 56, 255), (167, 150, 111, 255)
    for role in ("bollard", "nets", "boat", "stall"):
        image = Image.new("RGBA", (128, 96))
        draw = ImageDraw.Draw(image)

        def rect(x, y, width, height, color):
            draw.rectangle((x, y, x + width - 1, y + height - 1), fill=color)

        if role == "bollard":
            rect(22, 63, 20, 15, dark)
            rect(25, 54, 14, 20, wood)
            for y in (61, 65, 69):
                rect(22, y, 20, 2, rope)
        elif role == "nets":
            rect(8, 57, 43, 20, (38, 58, 59, 180))
            for i in range(7):
                rect(9 + i * 6, 58, 2, 18, (115, 132, 118, 255))
            for i in range(5):
                rect(9, 58 + i * 4, 40, 1, rope)
            rect(16, 58, 4, 3, (202, 197, 156, 255))
        elif role == "boat":
            for box in ((8, 57, 93, 17), (14, 51, 81, 29), (21, 47, 67, 36)):
                rect(*box, dark)
            rect(21, 51, 66, 28, wood)
            rect(25, 54, 58, 22, (69, 63, 53, 255))
            for x in (33, 51, 71):
                rect(x, 53, 5, 24, (168, 130, 84, 255))
            rect(30, 61, 68, 3, rope)
            rect(93, 58, 11, 9, wood)
            rect(10, 82, 82, 2, (93, 127, 139, 80))
        else:
            rect(10, 54, 50, 27, wood)
            rect(8, 50, 54, 7, rope)
            for x in (15, 51):
                rect(x, 70, 5, 19, dark)
            rect(12, 42, 45, 8, (72, 94, 88, 255))
            rect(12, 47, 45, 2, (167, 176, 149, 255))
        save_png(image, game / "Graphics/Pictures/Tidebound" / f"dock_{role}.png")


def generate(paths, maps):
    dock_props(paths.game)
    window_lights(paths, maps)
