"""Pack authored light masks using source tile identity, independent of atlas layout."""

from PIL import Image
from ..files import save_png, ruby


def window_lights(paths, maps):
    masks, indices, placements = [], {}, {}
    for area in maps:
        if area.light_mask is None:
            continue
        with Image.open(paths.root / "content/tilesets" / area.light_mask) as source:
            atlas = source.convert("RGBA")
        panes, tile_masks = [], {}
        for y, row in enumerate(area.layers[1]):
            for x, packed_tile in enumerate(row):
                tile = area.source_tiles.get(packed_tile, packed_tile)
                if tile < 384:
                    continue
                if tile not in tile_masks:
                    sx, sy = (tile - 384) % 8 * 32, (tile - 384) // 8 * 32
                    tile_masks[tile] = atlas.crop((sx, sy, sx + 32, sy + 32))
                mask = tile_masks[tile]
                if not mask.getchannel("A").getbbox():
                    continue
                pixels = mask.tobytes()
                if pixels not in indices:
                    indices[pixels] = len(masks)
                    masks.append(mask)
                panes.append([x, y, indices[pixels]])
        if panes:
            placements[area.id] = panes
    sheet = Image.new("RGBA", (32 * max(1, len(masks)), 32))
    for index, mask in enumerate(masks):
        sheet.paste(mask, (index * 32, 0))
    save_png(sheet, paths.game / "Graphics/Pictures/Tidebound/window_panes.png")
    (paths.root / "src/generated/window_lights.rb").write_text(
        "# Generated by maps/scenery.py.\nmodule Tidebound::Presentation\n"
        + "  WINDOW_LIGHTS = "
        + ruby(placements)
        + ".freeze\nend\n"
    )
