"""Bake static dock props and source-glass masks for the runtime sprites."""

from PIL import Image
from rubymarshal.reader import loads

from ..files import save_png
from .registry import ruby


def window_mask(atlas, tile):
    if tile < 384:
        return None
    x, y = (tile - 384) % 8, (tile - 384) // 8
    lighthouse = x == 6 and y in (447, 448)
    if not (
        (y == 230 and x in (2, 3))
        or (y == 232 and x == 0)
        or (y == 231 and x in (6, 7))
        or (y == 233 and x in (4, 5, 6))
        or (y == 226 and x == 5)
        or lighthouse
    ):
        return None
    mask = Image.new("RGBA", (32, 32))
    for py in range(32):
        for px in range(32):
            red, green, blue, alpha = atlas.getpixel((x * 32 + px, y * 32 + py))
            glass = (
                (red, green, blue) == (39, 47, 87)
                if lighthouse
                else alpha > 0 and blue >= 180 and green > red + 25 and blue > green + 25
            )
            if glass:
                mask.putpixel(
                    (px, py), (255, 218, 145, 235) if green > 165 else (234, 167, 79, 225)
                )
    return mask


def window_lights(paths, maps):
    tilesets = loads((paths.game / "Data/Tilesets.rxdata").read_bytes())
    masks, indices, placements = [], {}, {}
    for area in maps:
        if area.id not in (102, 108, 112):
            continue
        tileset = tilesets[area.tileset].attributes["@tileset_name"]
        with Image.open(paths.game / "Graphics/Tilesets" / f"{tileset}.png") as source:
            atlas = source.convert("RGBA")
        tiles = set(tile for row in area.layers[1] for tile in row)
        tile_masks = {tile: window_mask(atlas, tile) for tile in tiles}
        panes = []
        for y, row in enumerate(area.layers[1]):
            for x, tile in enumerate(row):
                mask = tile_masks[tile]
                if mask is None:
                    continue
                pixels = mask.tobytes()
                if pixels not in indices:
                    indices[pixels] = len(masks)
                    masks.append(mask)
                panes.append([x, y, indices[pixels]])
        placements[area.id] = panes
    sheet = Image.new("RGBA", (32 * max(1, len(masks)), 32))
    for index, mask in enumerate(masks):
        sheet.paste(mask, (index * 32, 0))
    save_png(sheet, paths.game / "Graphics/Pictures/Tidebound/window_panes.png")
    (paths.root / "src/generated/window_lights.rb").write_text(
        "# Generated by maps/scenery.py.\nmodule Tidebound::Presentation\n"
        + "  WINDOW_LIGHTS = "
        + ruby(placements)
        + ".freeze\nend\n"
    )
